# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "compass-wp"
  gem.homepage = "http://github.com/devonhumes/compass-wp"
  gem.license = "MIT"
  gem.summary = %Q{Create SASS/Compass compatible WordPress themes}
  gem.description = %Q{Create SASS/Compass compatible WordPress themes}
  gem.email = "devon.humes@gmail.com"
  gem.authors = ["Devon Humes"]
  gem.files = FileList["[A-Z]*", "{lib,sass,templates}/**/*"]
  # dependencies defined in Gemfile
end
Jeweler::RubygemsDotOrgTasks.new

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "compass-wp #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
